version: '3'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 wsgi:application
    volumes:
      - .:/app
      - static_data:/app/static
    ports:
      - "8000:8000"

volumes:
  static_data: