version: '3'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 wsgi:application
    volumes:
      - .:/app
      - static_data:/app/static

    environment:
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=beauty-app-db
      - DB_USER=devuser
      - DB_PASS=devpassword123
    
    ports:
      - "8000:8000"
    depends_on:
      - db
  
  db:
    image: postgres:12-alpine
    volumes:
        - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=beauty-app-db
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpassword123
    

volumes:
  postgres-data:
  static_data: